---
title: 异常
date: 2016-06-27 14:19:14
category: C++基础
tags: C++

---

## 异常

预防运行阶段错误。

### 异常终止(abort())
程序员可以调用abort()函数来终止程序。其位于< cstdlib >中，向标准错误流发送消息abnormal program termination(程序异常终止)(这个消息随编译器而异)，并终止程序。

### 数值检查防止异常终止
依靠程序来避免错误导致的程序终止(可靠性)，但是不需要经常这么做，因为程序过于冗长(一般以短小精悍实现目的为主)。
1. 对于有返回值的函数，可以讲返回值作为**指针**或引用传递(可以明显区分哪个参数用于答案)，将返回值设置为`bool`标识是否有错误，以便在调用中检查异常。

### 使用异常机制
使用三个关键字将控制权从程序的一个部分传递到另一部分的途径。
1. 使用`throw`引发异常；
2. 使用`catch`捕获特定异常(一个`try`块可以跟多个`catch`块)；
3. 使用`try`标志可能激活特定异常的代码块。

注意不一定抛出`exception`类，只要`throw`和`catch`的类型一致，异常就能捕获。例如：
```C++
throw "Now I throw a string"
catch(const char *s){
	...
}
```
1. `throw`会执行返回语句，终止函数执行；
2. 返回后在`catch`中进行异常匹配，如果没有匹配，将会调用`abort()`(这个行为可以修改)。

### 将对象作为异常类型
异常类型指的是抛出的类型(字符串或对象)，使用对象有两个好处：
1. 不同的异常类型(抛出对象)区分不同的函数引发的异常；
2. 这个返回的异常可以携带信息，便于确定引发异常的原因。

### C++11唯一支持的异常规范
C++98新增异常规范功能,他主要告诉用户函数可能引发异常，因此建议对这个函数使用异常机制
```C++
double test(double a) throw(const char *s);	//这项工作显然在注释中可以完成
```
C++11唯一支持的异常规范,指出这个函数不会引发异常
```C++
double test(double) noexpect
```

### 栈解退
不同于函数调用和返回的过程(释放栈到第一个返回地址停止)，如果引发异常，程序一直释放栈直到第一个位于`try`块中的返回地址(块中函数的返回地址`;`)，然后程序转移到`catch`块而不是调用函数的下一条语句.
1. 引发异常时栈解退到能引发异常的地方；
2. 和函数返回一样，栈中的自动类对象，类的析构函数将被调用；
3. 如果返回到最近的`try`块但是没有异常匹配，那么会继续栈解退，直到最后的`try`块，不匹配再调用`abort()`； 
4. `catch`块使用`exit(EXIT_FAILURE)`立即终止程序，异常机制依然负责释放自动变量。


### 异常特性
1. 如果返回到最近的`try`块但是没有异常匹配，那么会继续栈解退，直到最后的`try`块，不匹配再调用`abort()`；
2. 引发异常时，编译器总会创建一个临时拷贝，即使异常规范和`catch`块中指定的是引用(这是作用域的问题)。
3. <font color=red>有2的特性为什么还要使用引用？</font>这是因为基类引用可以引用派生类对象。因此在异常类继承层次结构中，更具体的异常类应该放在前边匹配(`catch`)，而在`throw`中，恰好相反(is-a关系，基类不是派生类，而派生类是基类)。

捕获一切异常(与`switch`中的`default`相似)：
```C++
catch (...){
	...	//statement
}
```

### exception类
[< exception >](http://www.cplusplus.com/reference/exception/exception/?kw=exception)头文件定义的`exception`类提供异常的语言支持(可以作为其他异常的基类)。
1. 公有虚成员函数`const char * what(){return "Your own description"}`，继承并隐藏后可以代替用字符串作为异常类型。

[< stdexcept >](http://www.cplusplus.com/reference/stdexcept/?kw=stdexcept)头文件从< exception >公有派生，定义了`logic_error`和`runtime_error`类。
1. 共7种异常类型(定义域错误，参数错误，空间不足，索引错误，范围溢出，上溢，下溢)，每个类有一个构造函数，提供方法`what()`返回的字符串。

[< new >](http://www.cplusplus.com/reference/new/bad_alloc/)头文件包含`bad_alloc`类的声明，从< exception >类公有派生而来，用来标识无法分配请求的内存量(new引发)。
1. 可以设计使`new`失败时返回空指针(这很合理)，C++提供了一种用法，指出不会抛出异常(用空指针代替)：
```C++
int *p = new (std::nothrow) int;
```

### 异常，类和继承
因为异常类也是类，所以可以继承，可以嵌套。
1. 从一个异常类中派生出另一个类；
2. 在类定义中嵌套异常类声明来组合异常，被嵌套类的方法定义式需要使用多个作用域解析符；
3. 嵌套的类(一般在类公有部分声明)本身可以被继承，可用作基类。

### 迷失方向的异常
即对未捕获异常或者意外异常的反应。
引发异常后两种情况会导致问题：
1. 异常规范没有异常匹配导致程序异常终止；
2. 异常不在函数中引发(或者函数没有异常规范)，必须捕获，否则也会异常终止。

#### 未捕获异常
程序意外终止时，不直接调用`abort()`函数，他通过`terminate()`函数调用`abort()`(默认)，因此可以修改`terminate()`调用的函数：
```C++
void myAbort(){
	...;
}
set_terminate(myAbort);
```

#### 意外异常
函数引发了异常规范中没有的异常。将调用`unexpected()`函数，这个函数调用`terminate()`(默认)，`terminate()`调用`abort()`,同理可修改这个默认值：
```C++
#include <exception>
void myUnexpected(){	//将意外异常转化为bad_exception
	throw bad_exception;	//如果不指定抛出的异常，会重新引发原来的异常
}
set_unexpected(myunexpected);
```
### 注意事项
可能内存泄漏，栈解退对动态管理的内存是ok的,但是程序员管理的内存，解退时可能释放指针造成内存泄漏，有两个解决方案：
1. 在调用的函数中也使用异常机制，抓取所有异常来管理内存并抛出原本想抛出的异常(这是在原本的异常层次中强行植入一层来执行想要的操作，原本程序的代码顺序没有任何变化)；
	+ 简单理解不同的地方，逻辑为，函数中有异常要先释放内存再抛出异常(那么不使用异常机制，在抛出异常前释放也ok?)。
2. 使用智能指针模板。